nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['https://myseriestime.local:4200']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
    expose_headers: ['Link']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    max_age: 3600
  paths:
    '^/api/': ~
