# config/services.yaml
parameters:
  serie:
    nb_par_page: 15
    backdrop_dir: 'uploads/backdrops'
    poster_dir: 'uploads/posters/series'
  anime:
    nb_par_page: 15
    backdrop_dir: 'uploads/backdrops'
    poster_dir: 'uploads/posters/animes'
  film:
    nb_par_page: 15
    backdrop_dir: 'uploads/backdrops'
    poster_dir: 'uploads/posters/films'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $apiKey: '%env(TMDB_API_KEY)%'

  App\Utils\AppExtension:
    tags:
      - { name: twig.extension }

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'