# config/services.yaml
parameters:
  serie:
    nb_par_page: 15
    backdrop_dir: 'uploads/backdrops'
    poster_dir: 'uploads/posters/series'
  anime:
    nb_par_page: 15
    backdrop_dir: 'uploads/backdrops'
    poster_dir: 'uploads/posters/animes'
  film:
    nb_par_page: 15
    backdrop_dir: 'uploads/backdrops'
    poster_dir: 'uploads/posters/films'
  user:
    profil_pictures_dir: 'uploads/profile_picture'

services:
  # Valeurs par défaut
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $apiKey: '%env(TMDB_API_KEY)%'

  # Extension Twig BackdropExtension
  App\Utils\BackdropExtension:
    class: App\Utils\BackdropExtension
    arguments:
      $projectDir: '%kernel.project_dir%'
    tags:
      - { name: twig.extension }

  # Autres extensions Twig
  App\Utils\:
    resource: '../src/Utils/'
    exclude:
      - '../src/Utils/BackdropExtension.php'

  # Autres services du projet
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'
      - '../src/Utils/'
